SitemapGenerator::Sitemap.default_host = "https://open.scrclr.com"
SitemapGenerator::Sitemap.sitemaps_path = '../../../public'
SitemapGenerator::Sitemap.create do
  add "/guides"

  add "/latest"
  add "/new"
  add "/unread"
  add "/top"

  add "/categories"
  add "/c/general"
  add "/c/security-headers"
  add "/c/guides"
  add "/c/csp-reports"
  add "/c/bughunt"
  add "/c/ssl-reminder"

  add "/c/general/l/latest"
  add "/c/general/l/new"
  add "/c/general/l/unread"
  add "/c/general/l/top"
  add "/c/security-headers/l/latest"
  add "/c/security-headers/l/new"
  add "/c/security-headers/l/unread"
  add "/c/security-headers/l/top"
  add "/c/guides/l/latest"
  add "/c/guides/l/new"
  add "/c/guides/l/unread"
  add "/c/guides/l/top"
  add "/c/csp-reports/l/latest"
  add "/c/csp-reports/l/new"
  add "/c/csp-reports/l/unread"
  add "/c/csp-reports/l/top"
  add "/c/bughunt/l/latest"
  add "/c/bughunt/l/new"
  add "/c/bughunt/l/unread"
  add "/c/bughunt/l/top"
  add "/c/ssl-reminder/l/latest"
  add "/c/ssl-reminder/l/new"
  add "/c/ssl-reminder/l/unread"
  add "/c/ssl-reminder/l/top"

  add "/projects"
  add "/projects/security-headers"
  add "/projects/csp-reports"
  add "/projects/bughunt"
  add "/projects/ssl-reminder"

  add "/security-headers"
  add "/csp-reports"
  add "/bughunt"
  add "/ssl-reminder"

  add "/nwslttr"
  add "/nwslttr/latest"
end
